### ISSUE TITLE
Splitting widget and app code

### ISSUE THREAD

**Issue by philipabbey** [house-of-abbey/GarminHomeAssistantWidget#1]
Copied from https://github.com/house-of-abbey/GarminHomeAssistant/issues/113.

### Goals

1. Having a code base for the app version without "legacy" widget code for achieving space to add new features.
2. Set the widget version to maintenance only mode (feature freeze, only bug fixing etc.)

### Proposal

New repository under "house-of-abbey" for the widget version. For example: "GarminHomeAssistantWidget".

Cloning the current code base into it. Removing all the "legacy" widget related code from the app repo and removing all the glance code in the widget version.

Set the widget repo to "maintenance only mode" by making this clear in the readme.

**Comment by Someone0nEarth** [comment]
At the moment, I replacing all URLs etc. to "GarminHomeAssistantWidget" repo: 

I propose, that we provide a dedicated version of the web-based editor for the widget version (so future changes in the "app" version won`t break it).

Suggested URL: https://house-of-abbey.github.io/GarminHomeAssistantWidget/web/

What do you think? @philipabbey @JosephAbbey

**Comment by josephabbey** [comment]
It is now available at that URL.

**Comment by philipabbey** [comment]
Just found a bug in `compile_sim.cmd` where I created but never used a variable.

```batch
--jungles %SRC%\%JUNGLE% ^
```

I realise you're on Linux, but could you amend the (simplified) file for the widget too please? I'll test on review.

Thanks.

**Comment by philipabbey** [comment]
I now have a version of the application working with widget code removed. See https://github.com/house-of-abbey/GarminHomeAssistant/tree/113-splitting-widget-and-app-code. I've started to look at the docs too, but some of that needs to be coordinated with your MR here.

**Comment by Someone0nEarth** [comment]
> Just found a bug in `compile_sim.cmd` where I created but never used a variable.
> 
> ```batchfile
> --jungles %SRC%\%JUNGLE% ^
> ```
> 
> I realise you're on Linux, but could you amend the (simplified) file for the widget too please? I'll test on review.
> 
> Thanks.

I added your version (and change the "default" device to "Venu"):

https://github.com/house-of-abbey/GarminHomeAssistantWidget/blob/1-splitting-widget-and-app-code/compile_sim.cmd

**Comment by Someone0nEarth** [comment]
> I now have a version of the application working with widget code removed. See https://github.com/house-of-abbey/GarminHomeAssistant/tree/113-splitting-widget-and-app-code. I've started to look at the docs too, but some of that needs to be coordinated with your MR here.

Yes, I wrote a proposal: 

https://github.com/house-of-abbey/GarminHomeAssistantWidget/compare/main...house-of-abbey:GarminHomeAssistantWidget:1-splitting-widget-and-app-code#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

I think, this can be use as a inspiration for the main repo.

**Comment by Someone0nEarth** [comment]
I will finally check my changes tomorrow, before I will do the PR.

**Comment by Someone0nEarth** [comment]
Just a reminder: The app store descriptions for the app and widget versions has to be updated too.

**Comment by philipabbey** [comment]
> Just found a bug in compile_sim.cmd where I created but never used a variable.\n\n--jungles %SRC%\\%JUNGLE% ^\nI realise you're on Linux, but could you amend the (simplified) file for the widget too please? I'll test on review.\n\nThanks.\n\nI added your version (and change the \"default\" device to \"Venu\"):

This will be fine as long as the Jungle file is renamed too.

Thanks

**Comment by philipabbey** [comment]
> Yes, I wrote a proposal:\n\nmain...house-of-abbey:GarminHomeAssistantWidget:1-splitting-widget-and-app-code#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5\n\nI think, this can be use as a inspiration for the main repo.

Will take a look, I've already started to make changes to the README for the application.

**Comment by Someone0nEarth** [comment]
> > Just found a bug in compile_sim.cmd where I created but never used a variable.\n\n--jungles %SRC%\\%JUNGLE% ^\nI realise you're on Linux, but could you amend the (simplified) file for the widget too please? I'll test on review.\n\nThanks.\n\nI added your version (and change the \"default\" device to \"Venu\"):
> 
> This will be fine as long as the Jungle file is renamed too.
> 
> Thanks

Yes, I renamed all files back to "default" names, as part of transforming the repo to widget only.

**Comment by Someone0nEarth** [comment]
On Tuesday, I did a PR for this branch.. but for the wrong repository 🙈 (because this repo is a fork from GarminHomeAssistant.. the default behavior is a PR for GarminHomeAssistant). So now for the right repo...

**Comment by philipabbey** [comment]
@JosephAbbey can you check the default behaviour here please?

**Comment by philipabbey** [comment]
@Someone0nEarth will look tomorrow. I have a PR nearly ready too.
