### ISSUE TITLE
Cached Menu will still be used, even if the setting is deactivated

### ISSUE THREAD

**Issue by Someone0nEarth** [house-of-abbey/GarminHomeAssistantWidget#12]
When the menu is cached and the setting for caching will be deactivated, the menu will be still shown as cached (and maybe even teh cached one will be used).

I would expect, that, when deactivating the menu caching option, that the menu will get fetched, even if a cached menu is in the storage.

What do you say to this @philipabbey ?

**Comment by philipabbey** [comment]
The original intention remains that if the cache is cleared, it is deleted.

https://github.com/house-of-abbey/GarminHomeAssistantWidget/blob/main/source%2FHomeAssistantApp.mc#L150

The user may no longer require the function, e.g. if the menu becomes volatile.

Philip

**Comment by philipabbey** [comment]
The original intention remains that if the cache is cleared, it is deleted.

https://github.com/house-of-abbey/GarminHomeAssistantWidget/blob/main/source%2FHomeAssistantApp.mc#L150

The user may no longer require the function, e.g. if the menu becomes volatile.

The root view should reflect the status change:

https://github.com/house-of-abbey/GarminHomeAssistantWidget/blob/main/source%2FRootView.mc#L136

Philip

**Comment by philipabbey** [comment]
Okay, I see the problem.

Unticking the option "Should the application cache the menu configuration?" should also clear the cache by inference ("Should the application clear the existing cache next time it is started?").

This is a bug with the application too.

**Comment by philipabbey** [comment]
It would be nice if [`Settings.update()`](https://github.com/house-of-abbey/GarminHomeAssistantWidget/blob/main/source/Settings.mc#L50) function could check if `mCacheConfig` is `false` and then `Storage.deleteValue("menu");` but then (`HomeAssistantApp.`)`mMenuStatus = WatchUi.loadResource($.Rez.Strings.Available) as Lang.String;` need fixing up too. So the control logic seems to get messy.
